//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller4e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESA_VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESA_VEHICULO()
        {
            this.SERVICIOS = new HashSet<SERVICIOS>();
        }
    
        public int INGR_ID { get; set; }
        public Nullable<int> ID_AUTO { get; set; }
        public Nullable<System.DateTime> INGR_FECHA_INGRESO { get; set; }
        public string INGR_RUT_CLIENTE { get; set; }
    
        public virtual AUTO AUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
    }
}
