//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller4e.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Taller4EEntities : DbContext
    {
        public Taller4EEntities()
            : base("name=Taller4EEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTO> AUTO { get; set; }
        public virtual DbSet<INGRESA_VEHICULO> INGRESA_VEHICULO { get; set; }
        public virtual DbSet<SERVICIOS> SERVICIOS { get; set; }
    }
}
